### ISSUE TITLE
Custom CSS should be in main.css

### ISSUE THREAD

**Issue by hmert** [naynco/nayn.wordpress#8]
```css
.menu-pod a{
    color: #e53491 !important;
    font-weight: bold !important;
}

.menu-pod:hover:after{
    background-color: #e53491 !important;
}

.h5p-iframe-wrapper{border:6px solid #fff}


@media (min-width: 320px) and (max-width: 480px) {
    .single-page-content-container{
        background-color:#fff;
    }
    .hero-slider h1{
        color:#000;
        text-shadow:1px 2px 0px #eee;
    }
    .entry-content{
        color:#000;
    }
    .entry-tag a{
        color:#000;
    }
    
}

#pwp-notification-button{
    font-size: 24px;
    bottom: unset;
    top: 1em;
    right: 1em;
    left: unset;}

@media only screen and (max-width: 767px) and (min-width: 200px){
    .single-page .post-prev {
        right: initial;
        left: 14px;
    }
 footer .footer-bottom .menu li{
     float:left;
    }
 }
@media only screen and (max-width: 1599px) and (min-width: 1201px){
    .single-category-page-content {
        top: 70px;
    }
}

@media screen and (min-width: 992px) {
    .header-top .menu{
        display: none;
    }
}

@media only screen and (max-width: 767px) and (min-width: 200px) {
    .hero-slider .owl-prev {
        right: initial;
        left: 14px;
    }
}

.entry-content{padding:0 20px}
```
